{{- with .Values -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hidebound
  namespace: {{ .namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hidebound
  template:
    metadata:
      labels:
        app: hidebound
    spec:
      containers:
        - name: hidebound-container
          image: "{{ .deployment.repository }}:{{ .deployment.image_tag }}"
          imagePullPolicy: {{ .deployment.image_pull_policy }}
          command:
          {{- range $item := .deployment.command }}
            - {{ $item }}
          {{- end }}
          args:
          {{- range $item := .deployment.args }}
            - {{ $item }}
          {{- end }}
          envFrom:
            {{- if .enable.env_configmap }}
            - configMapRef:
                name: hidebound-env-configmap
            {{- end }}
            {{- if .enable.env_secret }}
            - secretRef:
                name: hidebound-env-secret
            {{- end }}
          ports:
            - containerPort: {{ .service.target_port }}
          {{- if .enable.liveness_probe }}
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: {{ .service.target_port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- end }}
          {{- if .enable.readiness_probe }}
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: {{ .service.target_port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- end }}
          volumeMounts:
          {{- if .enable.ingress_volume }}
            - name: ingress
              mountPath: {{ .deployment.ingress.path }}
          {{- end }}
          {{- if .enable.staging_volume }}
            - name: staging
              mountPath: {{ .deployment.staging.path }}
          {{- end }}
          {{- if .enable.egress_volume }}
            - name: egress
              mountPath: {{ .deployment.egress.path }}
          {{- end }}
            {{- if .enable.repo_volume }}
            - name: repo
              mountPath: {{ .deployment.repo.path }}
            {{- end }}
      volumes:
      {{- if .enable.ingress_volume }}
        {{- if .deployment.ingress.nfs }}
        - name: ingress
          nfs:
             path: {{ .deployment.ingress.path }}
             server: {{ .deployment.ingress.nfs_server }}
             readOnly: false
        {{- else }}
        - name: ingress
          persistentVolumeClaim:
            claimName: hidebound-ingress-pvc
        {{- end }}
      {{- end }}
      {{- if .enable.staging_volume }}
        {{- if .deployment.staging.nfs }}
        - name: staging
          nfs:
             path: {{ .deployment.staging.path }}
             server: {{ .deployment.staging.nfs_server }}
             readOnly: false
        {{- else }}
        - name: staging
          persistentVolumeClaim:
            claimName: hidebound-staging-pvc
        {{- end }}
      {{- end }}
      {{- if .enable.egress_volume }}
        {{- if .deployment.egress.nfs }}
        - name: egress
          nfs:
             path: {{ .deployment.egress.path }}
             server: {{ .deployment.egress.nfs_server }}
             readOnly: false
        {{- else }}
        - name: egress
          persistentVolumeClaim:
            claimName: hidebound-egress-pvc
        {{- end }}
      {{- end }}
      {{- if .enable.repo_volume }}
        {{- if .deployment.repo.nfs }}
        - name: repo
          nfs:
             path: {{ .deployment.repo.path }}
             server: {{ .deployment.repo.nfs_server }}
             readOnly: false
        {{- else }}
        - name: repo
          persistentVolumeClaim:
            claimName: hidebound-repo-pvc
        {{- end }}
      {{- end }}
      imagePullSecrets:
        - name: image-pull-secret
{{- end -}}
