kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - path: "{{ .Values.ingress.path }}"
            pathType: Prefix
            backend:
              service:
                name: hidebound
                port:
                  number: {{ .Values.service.port }}
