version: "3.4"
volumes:
  cache:
services:
  hidebound:
    container_name: hidebound
    image: hidebound
    build:
      context: .
      dockerfile: hidebound.dockerfile
    ports:
      - '9012:9000'
      - '5080:80'
    userns_mode: "host"
    user: ubuntu
    volumes:
      - ../:/home/ubuntu/hidebound
      - ./jupyter:/home/ubuntu/.jupyter
      - ./ipython:/home/ubuntu/.ipython
      - ~/.ssh:/home/ubuntu/.ssh
      # - /mnt/storage:/mnt/storage
    working_dir: "/home/ubuntu/hidebound/python"
    command: "tail -f /dev/null"
