version: "3.4"
volumes:
  cache:
services:
  hidebound:
    container_name: hidebound
    image: hidebound
    build:
      context: .
      dockerfile: hidebound.dockerfile
    ports:
      - '9012:9000'
      - '5080:80'
    userns_mode: "host"
    user: root
    volumes:
      - ../:/root/hidebound
      - ./jupyter:/root/.jupyter
      - ./ipython:/root/.ipython
      - ~/.ssh:/root/.ssh
      # - /mnt/storage:/mnt/storage
    working_dir: "/root/hidebound/python"
    command: "tail -f /dev/null"
