version: "3.4"
volumes:
  cache:
services:
  hidebound:
    container_name: hidebound
    image: hidebound
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "2000:9000"
      - "2080:8080"
      - "2081:8081"
      - "2087:8087"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - dev-env
    volumes:
      - ../:/home/ubuntu/hidebound
      - ./jupyter:/home/ubuntu/.jupyter
      - ./ipython:/home/ubuntu/.ipython
      - ../artifacts:/tmp/dash_artifacts
      - ~/.ssh:/home/ubuntu/.ssh
      # - /mnt/storage:/mnt/storage
    working_dir: "/home/ubuntu"
    command: "tail -f /dev/null"
