# Run the hidebound service stack

# Required variables
#  - CURRENT_USER: The uid:gid value to ensure the bind mounted volume's
#                  permissions match the host
#  - REPO_PATH: The abs path to the user's repository on the host

version: '3.4'
volumes:
  cache:
services:

  hidebound:
    container_name: hidebound
    image: ${IMAGE}
    build:
      context: .
      dockerfile: hidebound.dockerfile
    ports:
      - '9012:9000'
      - '5000:5000'
    userns_mode: "host"
    user: root
    volumes:
      - ${REPO_PATH}:/root/hidebound
      - ${REPO_PATH}/docker/jupyter:/root/.jupyter
      # - /mnt/storage:/mnt/storage
    working_dir: "/root/hidebound/python"
    command: "tail -f /dev/null"
