version: "3.8"
volumes:
  cache:
services:
  hidebound:
    container_name: hidebound
    image: hidebound:dev
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "2000:9000"
      - "2080:8080"
      - "2081:8081"
      - "2087:8087"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - config/dev-env
    volumes:
      - ../:/home/ubuntu/hidebound
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
      - ../artifacts:/tmp/dash_artifacts
      # - /mnt/storage:/mnt/storage
    working_dir: "/home/ubuntu"
    command: "tail -f /dev/null"
