ZSH_THEME="henanigans"
export ZSH="/home/ubuntu/.oh-my-zsh"
plugins=(
    aws
    command-not-found
    common-aliases
    git
    npm
    pip
    python
    sudo
    fast-syntax-highlighting
    zsh-autosuggestions
    zsh-history-enquirer
)
source $ZSH/oh-my-zsh.sh
echo 'will cite' | parallel --citation >> /dev/null 2>&1
alias ll='ls -hlA'
alias tree='tree -Ca'
