namespace: hidebound

organization: k8s

container:
  image: k3d-dev-registry:5000/hidebound
  tag: latest
  repo: /mnt/storage/repos/hidebound
  storage_volume: /mnt/storage
  port: 80
  image_pull_policy: IfNotPresent
  command:
    ["python3.7", "/home/ubuntu/hidebound/python/hidebound/server/app.py"]
  env:
    - name: REPO_ENV
      value: "True"

service:
  port: 80

config:
  root_directory: /mnt/storage/projects
  hidebound_directory: /mnt/storage/hidebound
  specification_files:
    - /mnt/storage/hidebound/specifications/test_specifications.py
  include_regex:
  exclude_regex: \\.DS_Store
  write_mode: copy

ingress:
  path: /hidebound
